export enum KYCStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  VERIFIED = 'VERIFIED',
  CVL_SUBMITTED = 'CVL_SUBMITTED',
  CVL_VALIDATED = 'CVL_VALIDATED',
  REJECTED = 'REJECTED',
}

export enum DocumentSource {
  MANUAL_UPLOAD = 'MANUAL_UPLOAD',
  DIGILOCKER = 'DIGILOCKER',
}

export enum InternalStatus {
  PENDING = 'PENDING',
  DOCUMENTS_UPLOADED = 'DOCUMENTS_UPLOADED',
  OCR_COMPLETED = 'OCR_COMPLETED',
  FACE_VERIFIED = 'FACE_VERIFIED',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
  PENDING_REVIEW = 'PENDING_REVIEW',
}

export enum FinalStatus {
  INCOMPLETE = 'INCOMPLETE',
  COMPLETE = 'COMPLETE',
  REJECTED = 'REJECTED',
}
